=== RicardoCatana/ProgramareWeb_proiect/continut/validare.dtd
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume, prenume, varsta, adresa, limba, facultatea, email, telefon)>
<!ELEMENT adresa (strada, numar, localitate, judet, tara)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT limba (#PCDATA)> 
<!ELEMENT facultatea (#PCDATA)> 
<!ELEMENT email (#PCDATA)> 
<!ELEMENT telefon (#PCDATA)> 
<!ELEMENT strada (#PCDATA)> 
<!ELEMENT numar (#PCDATA)> 
<!ELEMENT localitate (#PCDATA)> 
<!ELEMENT judet (#PCDATA)> 
<!ELEMENT tara (#PCDATA)>

=== RicardoCatana/ProgramareWeb_proiect/continut/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane SYSTEM "validare.dtd">
<persoane>
        <persoana id="1">
            <nume>Popescu</nume>
            <prenume>Ion</prenume>
            <varsta>23</varsta>
            <adresa>
                <strada>str. Fulger</strada>
                <numar>22</numar>
                <localitate>Iasi</localitate>
                <judet>Iasi</judet>
                <tara>Romania</tara>
            </adresa>
            <limba>engleza</limba>
            <facultatea>Facultatea de Automatică și Calculatoare</facultatea>
            <email>ion.popescu@gmail.com</email>
            <telefon>0747264721</telefon>
    </persoana>

    <persoana id="2">
            <nume>Fortoes</nume>
            <prenume>Codrin-Musiala</prenume>
            <varsta>44</varsta>
            <adresa>
                <strada>str. Fantinilor</strada>
                <numar>61</numar>
                <localitate>Iasi</localitate>
                <judet>Iasi</judet>
                <tara>Romania</tara>
            </adresa>
            <limba>franceza</limba>
            <facultatea>Facultatea de Automatică și Calculatoare</facultatea>
            <email>forto.codrin@gmail.com</email>
            <telefon>0746462737</telefon>
    </persoana>

    <persoana id="3">
            <nume>Surdu</nume>
            <prenume>Gabriel</prenume>
            <varsta>21</varsta>
            <adresa>
                <strada>str. Renasterii</strada>
                <numar>12</numar>
                <localitate>Husi</localitate>
                <judet>Vaslui</judet>
                <tara>Roamania</tara>
            </adresa>
            <limba>germana</limba>
            <facultatea>Facultatea de Automatică și Calculatoare</facultatea>
            <email>surdu.gabi@yahoo.com</email>
            <telefon>0738291847</telefon>
    </persoana>
</persoane>
